In [2]:
import pandas as pd
import numpy as np

segment = pd.read_csv(r"D:\RFM Analysis\customer_segmentation_monthly.csv")

In [3]:
segment

,customer_unique_id,first_purchase_date,first_purchase_month,snapshot_month_start,snapshot_month_end,monthly_orders,monthly_monetary_value,frequency,monetary_value,last_purchase_date,recency_days,recency_score,frequency_score,monetary_score,rfm_score,customer_segment
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-05-01,2018-05-31,1,141.90,1,141.90,2018-05-10,21,5,5,4,554,Champions
1,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-06-01,2018-06-30,0,0.00,1,141.90,2018-05-10,51,5,5,4,554,Champions
2,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-07-01,2018-07-31,0,0.00,1,141.90,2018-05-10,82,5,5,4,554,Champions
3,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-08-01,2018-08-31,0,0.00,1,141.90,2018-05-10,113,4,5,4,454,Loyal Customers
4,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07,2018-05-01,2018-05-01,2018-05-31,1,27.19,1,27.19,2018-05-07,24,5,5,1,551,Champions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789088,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-04-01,2018-04-30,0,0.00,1,71.56,2017-05-02,363,1,1,2,112,Hibernating
789089,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-05-01,2018-05-31,0,0.00,1,71.56,2017-05-02,394,1,1,2,112,Hibernating
789090,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-06-01,2018-06-30,0,0.00,1,71.56,2017-05-02,424,1,1,2,112,Hibernating
789091,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-07-01,2018-07-31,0,0.00,1,71.56,2017-05-02,455,1,1,2,112,Hibernating
789092,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-08-01,2018-08-31,0,0.00,1,71.56,2017-05-02,486,1,1,2,112,Hibernating

Ranking Customers by monetary value in each month

In [4]:

segment["value_percentile"] = (
    segment
    .groupby("snapshot_month_end")["monetary_value"]
    .rank(method="min", pct=True)
)

Dividing Customers into high, medium and low segments

In [ ]:

segment["Customer_Value"] = np.select(
    [
        segment["value_percentile"] >= 0.80,  # Top 20%
        segment["value_percentile"] >= 0.50   # Next 30%
    ],
    [
        "High Value",
        "Medium Value"
    ],
    default="Low Value"
)

In [6]:
segment

,customer_unique_id,first_purchase_date,first_purchase_month,snapshot_month_start,snapshot_month_end,monthly_orders,monthly_monetary_value,frequency,monetary_value,last_purchase_date,recency_days,recency_score,frequency_score,monetary_score,rfm_score,customer_segment,value_percentile,Customer_Value
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-05-01,2018-05-31,1,141.90,1,141.90,2018-05-10,21,5,5,4,554,Champions,0.636754,Medium Value
1,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-06-01,2018-06-30,0,0.00,1,141.90,2018-05-10,51,5,5,4,554,Champions,0.635070,Medium Value
2,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-07-01,2018-07-31,0,0.00,1,141.90,2018-05-10,82,5,5,4,554,Champions,0.633751,Medium Value
3,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10,2018-05-01,2018-08-01,2018-08-31,0,0.00,1,141.90,2018-05-10,113,4,5,4,454,Loyal Customers,0.634622,Medium Value
4,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07,2018-05-01,2018-05-01,2018-05-31,1,27.19,1,27.19,2018-05-07,24,5,5,1,551,Champions,0.021025,Low Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789088,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-04-01,2018-04-30,0,0.00,1,71.56,2017-05-02,363,1,1,2,112,Hibernating,0.311770,Low Value
789089,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-05-01,2018-05-31,0,0.00,1,71.56,2017-05-02,394,1,1,2,112,Hibernating,0.310902,Low Value
789090,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-06-01,2018-06-30,0,0.00,1,71.56,2017-05-02,424,1,1,2,112,Hibernating,0.309604,Low Value
789091,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-07-01,2018-07-31,0,0.00,1,71.56,2017-05-02,455,1,1,2,112,Hibernating,0.308712,Low Value
789092,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02,2017-05-01,2018-08-01,2018-08-31,0,0.00,1,71.56,2017-05-02,486,1,1,2,112,Hibernating,0.309690,Low Value

Filtering to specific columns

In [ ]:
customer_value = segment[
    [
        "customer_unique_id",
        "snapshot_month_start",
        "snapshot_month_end",
        "monetary_value",
        "value_percentile",
        "Customer_Value"
    ]
]

In [9]:
customer_value

,customer_unique_id,snapshot_month_start,snapshot_month_end,monetary_value,value_percentile,Customer_Value
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-01,2018-05-31,141.90,0.636754,Medium Value
1,0000366f3b9a7992bf8c76cfdf3221e2,2018-06-01,2018-06-30,141.90,0.635070,Medium Value
2,0000366f3b9a7992bf8c76cfdf3221e2,2018-07-01,2018-07-31,141.90,0.633751,Medium Value
3,0000366f3b9a7992bf8c76cfdf3221e2,2018-08-01,2018-08-31,141.90,0.634622,Medium Value
4,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-01,2018-05-31,27.19,0.021025,Low Value
...,...,...,...,...,...,...
789088,ffffd2657e2aad2907e67c3e9daecbeb,2018-04-01,2018-04-30,71.56,0.311770,Low Value
789089,ffffd2657e2aad2907e67c3e9daecbeb,2018-05-01,2018-05-31,71.56,0.310902,Low Value
789090,ffffd2657e2aad2907e67c3e9daecbeb,2018-06-01,2018-06-30,71.56,0.309604,Low Value
789091,ffffd2657e2aad2907e67c3e9daecbeb,2018-07-01,2018-07-31,71.56,0.308712,Low Value
789092,ffffd2657e2aad2907e67c3e9daecbeb,2018-08-01,2018-08-31,71.56,0.309690,Low Value

Saving Customer_Value as a CSV file

In [8]:
customer_value.to_csv("customer_value.csv", index=False)